apiVersion: agill.apps/v1alpha1
kind: S3
metadata:
  name: example-s3
spec:
  region: us-east-1
  ## valid values: private,public-read,public-read-write,authenticated-read
  bucketACL: private
  bucketName: agill-test-bucket
  ## only available when creating the bucket for the first time
  enableObjectLock: false
  enableVersioning: true
  enableTransferAcceleration: true
  bucketPolicy: |
    {
        "Version":"2012-10-17",
        "Statement":[{
                "Sid":"PublicRead",
                "Effect":"Allow",
                "Principal": "*",
                "Action":["s3:GetObject"],
                "Resource":["arn:aws:s3:::agill-test-bucket/*"]
        }]
    }
  iamUser:
    username: agill-test-bucket
