apiVersion: agill.apps/v1alpha1
kind: S3
metadata:
  name: example-s3
spec:
  region: us-east-1
  ## valid values: private,public-read,public-read-write,authenticated-read
  bucketACL: private
  bucketName: agill-test-bucket
  ## only available when creating the bucket for the first time
  enableObjectLock: false
  enableVersioning: true
  enableTransferAcceleration: true
  iamUser:
    username: agill-test-bucket
