apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: s3s.agill.apps
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.bucketName
    name: bucket-name
    type: string
  - JSONPath: .spec.iamUser.username
    name: IAM-User
    type: string
  - JSONPath: .status.status
    name: Status
    type: string
  group: agill.apps
  names:
    kind: S3
    listKind: S3List
    plural: s3s
    singular: s3
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: S3 is the Schema for the s3s API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: S3Spec defines the desired state of S3
          properties:
            bucketACL:
              description: The canned ACL to apply to the bucket.
              enum:
              - private
              - public-read
              - public-read-write
              - authenticated-read
              type: string
            bucketName:
              type: string
            bucketPolicy:
              type: string
            enableObjectLock:
              description: Specifies whether you want S3 Object Lock to be enabled
                for the new bucket.
              type: boolean
            enableTransferAcceleration:
              description: Decides whether transfer acceleration should be enabled.
                Defaults to false
              type: boolean
            enableVersioning:
              description: Decides whether versioning should be enabled. Defaults
                to false.
              type: boolean
            iamUser:
              properties:
                username:
                  type: string
              required:
              - username
              type: object
            region:
              type: string
          required:
          - bucketACL
          - bucketName
          - region
          type: object
        status:
          description: S3Status defines the observed state of S3
          properties:
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
