apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-operator
  namespace: s3-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s3-operator
  template:
    metadata:
      labels:
        name: s3-operator
    spec:
      serviceAccountName: s3-operator
      containers:
        - name: s3-operator
          image: agill17/s3-operator:0.6.1
          imagePullPolicy: Always
          command:
          - s3-operator
          args:
          - --zap-devel
          env:
            - name: AWS_ACCESS_KEY_ID
              value: <>
            - name: AWS_SECRET_ACCESS_KEY
              value: <>
            - name: syncPeriod
              value: 10
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "s3-operator"
