name: Build And Push
on: [push]
env:
  GO111MODULE: on
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Operator-SDK Build
        uses: xunholy/operator-sdk-github-action@master
        id: operator-sdk
        env:
          RELEASE_VERSION: v0.15.2
        with:
          image: agill17/s3-operator
          tag: latest
          dirPath: .

      - name: Publish to Registry
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push "${{steps.operator-sdk.outputs.image}}"
