name: Build
on:
  push:
jobs:
  opreator-build:
    name: Build operator
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: s3-operator

      - name: Operator-sdk build
        uses: dxas90/operator-sdk-github-action@v3
        id: operator-sdk
        env:
          RELEASE_VERSION: v0.15.2
        with:
          image: "docker.pkg.github.com/${{github.repository}}/operator"
          tag: "${{github.sha}}"
          dirPath: ./s3-operator

      - name: Publish docker image
        env:
          GITSHA_IMAGE_TAG: docker.pkg.github.com/${{github.repository}}/operator:${{github.sha}}
          LATEST_IMAGE_TAG: docker.pkg.github.com/${{github.repository}}/operator:latest
        run: |
          docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
          docker tag  $GITSHA_IMAGE_TAG $LATEST_IMAGE_TAG
          docker push $GITSHA_IMAGE_TAG
          docker push $LATEST_IMAGE_TAG
