name: Operator SDK CI
on:
  push:
jobs:
  opreatorbuild:
    name: Package Chart
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: s3-operator

      - name: Build Container
        uses: xunholy/operator-sdk-action@master
        id: operator-sdk
        with:
          image: "docker.pkg.github.com/${{github.repository}}/operator"
          tag: "${{github.sha}}"
          dirPath: ./s3-operator

      - name: Build the Docker image
        env:
          CONTAINER_IMAGE: docker.pkg.github.com/${{github.repository}}/operator:${{github.sha}}
          CONTAINER_IMAGE_LATEST: docker.pkg.github.com/${{github.repository}}/operator:latest
        run: |
          docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
          docker tag  $CONTAINER_IMAGE $CONTAINER_IMAGE_LATEST
          docker push $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE_LATEST
