name: Build And Push
on: [push]
env:
  GO111MODULE: on
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out code
        uses: actions/checkout@v1

      - name: Operator-SDK Build
        uses: dxas90/operator-sdk-github-action@v3
        id: operator-sdk
        env:
          RELEASE_VERSION: v0.15.2
        with:
          image: agill17/s3-operator
          tag: latest

      - name: Debug
        if: ${{ always() }}
        run: |
          pwd
          ls -R build || true
          ls -lrt build/_output/bin
          ls -lrt build/_output/bin/workspace
          
      - name: Publish to Registry
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push "${{steps.operator-sdk.outputs.image}}"
